In [5]:
import pandas as pd
from sklearn.utils import resample

Due to high runtime of mixed effect models, we will reduce the training size to overcome this. Since we have unbalanced classes we will try to reduce dataset by reducing majority classes to improve upon the training

In [2]:
train = pd.read_csv('../data/train_transformed.csv')
train.head()

,job_type_blue-collar,job_type_entrepreneur,job_type_housemaid,job_type_management,job_type_retired,job_type_self-employed,job_type_services,job_type_student,job_type_technician,job_type_unemployed,...,default,housing_loan,personal_loan,communication_type,prev_campaign_outcome,prev_campaign_contact,balance,last_contact_duration,num_contacts_in_campaign,num_contacts_prev_campaign
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,no,no,yes,cellular,other,yes,934.0,143.0,2.0,1
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,no,no,no,cellular,unknown,no,656.0,101.0,4.0,0
2,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,no,yes,no,unknown,unknown,no,2.0,127.0,3.0,0
3,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,no,yes,no,cellular,unknown,no,1352.0,49.0,2.0,0
4,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,no,no,no,cellular,unknown,no,2880.0,163.0,1.0,0

In [3]:
train.shape

(24392, 52)

In [4]:
train_0 = train.query('term_deposit_subscribed == 0')
train_1 = train.query('term_deposit_subscribed == 1')
train_0.shape, train_1.shape

((21753, 52), (2639, 52))

In [13]:
train_0_ds = resample(train_0, replace=False, n_samples=len(train_1), random_state=100)
train_ds = pd.concat([train_0_ds, train_1])
train_ds.reset_index(drop=True, inplace=True)
train_ds

,job_type_blue-collar,job_type_entrepreneur,job_type_housemaid,job_type_management,job_type_retired,job_type_self-employed,job_type_services,job_type_student,job_type_technician,job_type_unemployed,...,default,housing_loan,personal_loan,communication_type,prev_campaign_outcome,prev_campaign_contact,balance,last_contact_duration,num_contacts_in_campaign,num_contacts_prev_campaign
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,no,yes,yes,cellular,failure,yes,2978.0,109.0,1.0,2
1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,no,yes,yes,unknown,unknown,no,1542.0,178.0,9.0,0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,no,yes,no,cellular,failure,yes,219.0,162.0,5.0,7
3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,no,no,yes,telephone,unknown,no,2534.0,477.0,2.0,0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,no,no,no,telephone,unknown,no,544.0,59.0,1.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5273,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,no,yes,yes,cellular,other,yes,701.0,1275.0,2.0,2
5274,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,no,yes,no,cellular,failure,yes,542.0,1575.0,1.0,4
5275,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,no,yes,no,unknown,unknown,no,127.0,2450.0,2.0,0
5276,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,no,yes,no,cellular,unknown,no,614.0,356.0,1.0,0
5277,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,no,yes,no,cellular,failure,yes,298.0,432.0,4.0,1

In [14]:
train_ds['term_deposit_subscribed'].value_counts()

0    2639
1    2639
Name: term_deposit_subscribed, dtype: int64

In [15]:
train_ds.to_csv('../data/train_transformed_ds.csv')